### ISSUE TITLE
Adjust doors3 models

### ISSUE THREAD

**Issue by TumeniNodes** [TumeniNodes/pkarcs#3]
The models for doors3 need to be adjusted to stop the flickering.
Not sure of just lowering the entire models a fraction of a pixel will work, or if the entire models need to be reduced in height?
But the issue is definitely due to slightly improper positioning of the models.

Lining them up side by side with the standard doors shows the amount they are off.
![screenshot_20190902_154114](https://user-images.githubusercontent.com/18484258/64201766-6eefcb00-ce5d-11e9-9f90-b62704a22129.jpg)

**Comment by NathanSalapat** [comment]
I would have gotten this fixed but I ran into an error with your textures. All the textures for the three node tall doors are 47px tall rather than the 48 px that three nodes should be. I realize that the models are 1 px shorter than the full three nodes, so I can edit the UV maps so the pixels all line up, as the current mapping is as if the texture is 48px tall. It doesn't make any difference to me which you want, but I would like to know before I go and edit all of them.

**Comment by TumeniNodes** [comment]
The doors are 47pixels high, as the 48th is taken by the top of the arcs
What ever you feel works best is fine with me, I trust your judgement...
And as long as the top & bottom hinges have a single node space from the edge I'm happy

**Comment by NathanSalapat** [comment]
Well I'd personally use 48px tall textures, but if I change the UV map that way all the images will need to be edited. I can add a single color strip on the top or bottom of one to get everything setup and leave the rest for you to change. I read someplace that image textures work best when they are divisible by two.

**Comment by TumeniNodes** [comment]
I _really_ dont feel like editing _all_ those textures again :D 
But it _is_ the right way to go... wondering why I wasn't realizing this... the textures for the standard doors I did 16x32.
Go for it ; )

**Comment by NathanSalapat** [comment]
If you want I can change them, I bet I can write a quick little macro that gimp can run and change them all.

**Comment by TumeniNodes** [comment]
That's up to you... it's just adding a top run of pixels. Would take about 10 minutes by hand
Did you get a look at my crazy mapping yet? :P it keeps the wood grains along the top and bottom

**Comment by NathanSalapat** [comment]
I'll do it. Got all the meshes finished, will have a pull request soon.

**Comment by TumeniNodes** [comment]
The doors in the doors mod should be done the same way... notice the pixels are much sharper using the single door image...
The double UV texture causes stretching to wrap the model which blurs the image during rendering.. I've thought about doing a PR for that but not sure it would go through, especially since sofar did that not that long ago

**Comment by TumeniNodes** [comment]
> I'll do it. Got all the meshes finished, will have a pull request soon.

Cool, thanks
